Infrastructure: add workaround clang-tidy-review directory bug (#8597)
<!-- Keep the title short & concise so anyone non-technical can
understand it,
     the title appears in PTB changelogs -->
#### Brief overview of PR changes/additions
Add workaround clang-tidy-review directory bug which causes clang-tidy
not to work:

> error: error reading '/github/workspace/': Is a directory
[clang-diagnostic-error]
https://github.com/ZedThree/clang-tidy-review/issues/157
#### Motivation for adding to Mudlet
https://github.com/Mudlet/Mudlet/pull/8595
#### Other info (issues closed, discussion etc)
error: error reading '/github/workspace/': Is a directory
[clang-diagnostic-error]